clean up a bit more with case statement (SOFTWARE-1080)
git-svn-id: https://vdt.cs.wisc.edu/svn/software/rsv/trunk@19957 4e558342-562e-0410-864c-e07659590f8c

diff --git a/rsv-core/init/rsv.init b/rsv-core/init/rsv.init
--- a/rsv-core/init/rsv.init
+++ b/rsv-core/init/rsv.init
@@ -49,40 +49,40 @@ start() {
 __status_codes__
 
 status() {
+    test -e $REDHAT_LOCKFILE
+    lock_status=$?
     ccq_output=`$CONDOR_EXE_QUEUE rsv 2>&1`
     ccq_status=$?
-    ccq_summary=`echo "$ccq_output" | tail -1`
-    case $ccq_summary in
+    ccq_summary_line=`echo "$ccq_output" | tail -1`
+    case $ccq_summary_line in
         "0 jobs"* ) rsv_jobs_in_queue=N ;;
         *         ) rsv_jobs_in_queue=Y ;;
     esac
 
-    if [ -e $REDHAT_LOCKFILE ] && [ $ccq_status -eq 0 ]; then
-        if [ $rsv_jobs_in_queue = Y ]; then
-            echo "RSV is running.  Current condor-cron queue:"
-            echo "$ccq_output"
-            RETVAL=0
-        else
-            echo "RSV lock file exists, but condor-cron queue is empty:"
-            echo "$ccq_output"
-            RETVAL=2
-        fi
-    elif [ -e $REDHAT_LOCKFILE ] && [ $ccq_status -ne 0 ]; then
-        echo "RSV lock file exists, but condor-cron is not running."
-        RETVAL=2
-    elif [ ! -e $REDHAT_LOCKFILE ] && [ $ccq_status -eq 0 ]; then
-        if [ $rsv_jobs_in_queue = Y ]; then
-            echo "RSV lock file missing, but jobs in condor-cron queue:"
-            echo "$ccq_output"
-            RETVAL=0
-        else
-            echo "RSV is stopped."
-            RETVAL=3
-        fi
-    elif [ ! -e $REDHAT_LOCKFILE ] && [ $ccq_status -ne 0 ]; then
-        echo "RSV lock file does not exist and condor-cron is not running."
-        RETVAL=3
-    fi
+    case $lock_status:$ccq_status:$rsv_jobs_in_queue in
+      0:0:Y)
+          echo "RSV is running.  Current condor-cron queue:"
+          echo "$ccq_output"
+          RETVAL=0 ;;
+      0:0:N)
+          echo "RSV lock file exists, but condor-cron queue is empty:"
+          echo "$ccq_output"
+          RETVAL=2 ;;
+      0:*:*)
+          echo "RSV lock file exists, but condor-cron is not running."
+          RETVAL=2 ;;
+      *:0:Y)
+          echo "RSV lock file missing, but jobs are in condor-cron queue:"
+          echo "$ccq_output"
+          RETVAL=0 ;;
+      *:0:N)
+          echo "RSV is stopped."
+          RETVAL=3 ;;
+      *:*:*)
+          echo "RSV lock file is not present and condor-cron is not running."
+          RETVAL=3 ;;
+    esac
+
     return $RETVAL
 }
 
